service:
  type: ClusterIP
  port: 3306

persistence:
  enabled: true
  storageClass: ""
  accessModes:
  - ReadWriteOnce
  size: 8Gi

resources:
  requests:
    memory: 256Mi
    cpu: 250m
  limits:
    memory: 512Mi
    cpu: 500m

nodeSelector: {}
tolerations: []
affinity: {}
